=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/REPASO/schema3/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="equipos_esp">
    <xs:complexType mixed="false"> <!--mixed: lleva enunciados dentro-->
        <xs:sequence>
            <xs:element name="equipo" maxOccurs="unbounded"> 
                <xs:complexType mixed="true">
                <xs:sequence>
                    <xs:element name="nombre">
                        <xs:complexType mixed="true">
                            <xs:attribute name="sigla" type="xs:string" default=""/>
                            <!--elemento lleva contenido-->
                        </xs:complexType>  
                    </xs:element>
                    <xs:element name="valoracion" type="xs:double"/>
                    <xs:element name="champion" type="xs:boolean"/>
                    <xs:element name="deporte" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="pais" type="xs:string" fixed="EspaÃ±a"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="observacion" type="xs:string"/>
            <xs:element name="division" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/REPASO/schema3/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos_esp xsi:noNamespaceSchemaLocation="ejemplo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<equipo pais="España">
    el mejor equipo del mundo
    <nombre sigla="FCB">Futbol club barcelona</nombre>
    <valoracion>100000.0</valoracion>
    <champion>true</champion>
    <deporte>Futbol</deporte>
<deporte>Baloncesto</deporte>
    <deporte>Futbol sala</deporte>
</equipo>
<equipo pais="España">
    xd
    <nombre sigla="RMA">Real Madrid CF</nombre>
    <valoracion>10.0</valoracion>
    <champion>true</champion>
    <deporte>Futbol</deporte>
<deporte>Baloncesto</deporte> 
</equipo>
<observacion>Son equipos de deporte de españa</observacion>
<division>1</division>
</equipos_esp>
