<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATALOG [
<!ELEMENT CATALOG (PRODUCT+)>
<!ELEMENT PRODUCT (SPECIFICATIONS+, OPTIONS?, PRICE+, NOTES?)>
<!ATTLIST PRODUCT NAME CDATA #IMPLIED
CATEGORY (HandTool|Table|Shop-Professional) "HandTool"
PARTNUM CDATA #IMPLIED
PLANT (Pittsburgh|Milwaukee|Chicago) "Chicago"
INVENTORY (InStock|Backordered|Discontinued) "InStock">
<!ELEMENT SPECIFICATIONS (#PCDATA)>
<!ATTLIST SPECIFICATIONS WEIGHT CDATA #IMPLIED
POWER CDATA #IMPLIED>
<!ELEMENT OPTIONS (#PCDATA)>
<!ATTLIST OPTIONS 
FINISH (MetalPolished|Matte) "Matte"
ADAPTER (Included|Optional|NotApplicable) "Included"
CASE (HardShellSoft|NotApplicable) "HardShellSoft">
<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST PRICE MSRP CDATA #IMPLIED
WHOLESALE CDATA #IMPLIED
STREET CDATA #IMPLIED
SHIPPING CDATA #IMPLIED>
<!ELEMENT NOTES (#PCDATA)>
]>
<CATALOG >
    <PRODUCT NAME="P1" CATEGORY="Shop-Professional" PARTNUM="123" PLANT="Chicago" INVENTORY="InStock">
        <SPECIFICATIONS WEIGHT="123" POWER="ON"></SPECIFICATIONS>
        <OPTIONS FINISH="MetalPolished" ADAPTER="Optional" CASE="HardShellSoft"></OPTIONS>
        <PRICE MSRP="ABC" WHOLESALE="" STREET="GROVE STREET" SHIPPING=""></PRICE>
        <NOTES></NOTES>
    </PRODUCT>
</CATALOG>