=== cronoxxxx/Lenguaje-Marcas-1DAM/MaterialExamen/EjemplosSchemas/schema5/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transportes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aereos" type="aereos" maxOccurs="2"></xs:element>
                <xs:element name="terrestres" type="terrestres"></xs:element>
                <xs:element name="numeros" type="valores"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="aereos" >
        <xs:choice>
            <xs:element name="avion" type="xs:string" />
            <xs:element name="helicoptero" type="xs:string" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="terrestres">
        <xs:choice>
            <xs:element name="moto" type="xs:string" />
            <xs:element name="coche" type="xs:string" />
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="valores">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="3" />
            <xs:enumeration value="2" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/REPASO/schema5/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<transportes xsi:noNamespaceSchemaLocation="ejemplo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<aereos>
    <avion>vuela lejos</avion>
</aereos>
<aereos>
    <helicoptero>vuela lejos menos</helicoptero>
</aereos>
<terrestres>
    <moto>run run</moto>
</terrestres>
<numeros>2</numeros>
</transportes>
