=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/EXAMPLES/example2/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd" name="Song">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id" type="xs:integer" />
                <xs:element name="Title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="6" />
                            <xs:maxLength value="12" />
                            <xs:pattern value="[A-Z]([a-z])*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Published" type="xs:boolean" default="0" />
                <xs:element name="DatePub" type="xs:date" />
                <xs:element name="Artist" type="xs:string" />
                <xs:element name="Company" type="xs:string" fixed="ACME" />
                <xs:element name="Password">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="6" />
                            <xs:maxLength value="12" />
                            <xs:pattern value="[a-zA-Z_]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Salary">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="7" />
                            <xs:fractionDigits value="2" />
                            <xs:minInclusive value="10000" />
                            <xs:maxInclusive value="90000" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="JobTitle">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Manager" />
            <xs:enumeration value="Developer" />
            <xs:enumeration value="Disc Jockey" />
        </xs:restriction>
    </xs:simpleType>
</xs:element>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:string" default="EN" />
            <xs:attribute name="prod" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/EXAMPLES/example2/e1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Song xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd" lang="EN" prod="XML">
    <Id>123</Id>
    <Title>Titanium</Title>
    <Published>true</Published>
    <DatePub>2012-10-09</DatePub>
    <Artist>David Guetta</Artist>
    <Company>ACME</Company>
    <Password>David_xd</Password>
    <Salary>12345.65</Salary>
    <JobTitle>Disc Jockey</JobTitle>
</Song>
