=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/REPASO/schema2/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="marcadores">
    <xs:complexType >
        <xs:sequence>

            <xs:element name="nada" maxOccurs="2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="marcador"  type="xs:string"/> <!--Igual que no ponerlo-->
                        <xs:element name="veces"  type="xs:string"/> <!--No podemos poner solo un valor minOccurs mayor que uno-->
                        <xs:element name="tiempo_seg"  maxOccurs="3" type="xs:double"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="nada2" maxOccurs="2">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="marcador"  type="xs:string"/> <!--Igual que no ponerlo-->
                        <xs:element name="veces"  type="xs:string"/> <!--No podemos poner solo un valor minOccurs mayor que uno-->
                        <xs:element name="tiempo_seg"  maxOccurs="3" type="xs:double"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>

            <xs:element name="nada3" maxOccurs="2">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="marcador"  type="xs:string"/> <!--Igual que no ponerlo-->
                        <xs:element name="veces"  type="xs:string"/> <!--No podemos poner solo un valor minOccurs mayor que uno-->
                        <xs:element name="tiempo_seg" type="xs:double"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== cronoxxxx/Lenguaje-Marcas-1DAM/XML/REPASO/schema2/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xsi:noNamespaceSchemaLocation="ejemplo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
     <!--sequence: tenemos que poner todos los elementos-->
    <nada>
        <marcador>el marcador</marcador>
        <veces>1</veces>
        <tiempo_seg>1.6</tiempo_seg>
        <tiempo_seg>1.6</tiempo_seg>
        <tiempo_seg>1.6</tiempo_seg>
    </nada>
    <nada>
        <marcador>el marcador</marcador>
        <veces>1</veces>
        <tiempo_seg>1.6</tiempo_seg>
        <tiempo_seg>1.6</tiempo_seg>
        <tiempo_seg>1.6</tiempo_seg>
    </nada>
    <!--choice: solo nos permite elegir un elemento-->
    <nada2>
        <tiempo_seg>1.6</tiempo_seg>
    </nada2>
    <!--all: pueden ir en cualquier orden, pero sin maxOccurs o minOccurs-->
    <nada3>
        <tiempo_seg>1.6</tiempo_seg>
        <marcador>el marcador</marcador>
        <veces>1</veces>
    </nada3>
</marcadores>
